name: CI
on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
jobs:
    build-and-push-docker:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: artixkrieger/multi-tenant-order-service
            IMAGE_TAG: build-${{ github.run_number }}
            DOCKER_BUILDKIT: 1 # Enable BuildKit
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker Image
              run: docker buildx build --platform linux/amd64 -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .
            - name: Push Docker Image to DockerHub
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
